### PR TITLE
Create Governance document

### PR DESCRIPTION
**Pull request by containers-ai-user**
Alameda need GOVERNANCE rules for CNCF organization

### CODE REVIEW

**Comment by containers-ai-user** [comment]
Good

**Comment by containers-ai-user** [comment]
good

**Comment by containers-ai-user** [comment]
Good

**Comment by containers-ai-user** [comment]
Good

**Comment by blueranger** [comment]
Jeremy suggested using Rook's rule. We don't have to decide the Governance soon. Let us keep this thread open for further discussion.

Rook's link
https://github.com/rook/rook/blob/master/GOVERNANCE.md

**Pull request merged**
